package Scanner;

public enum Reservadas {
	BOOLEAN, TRUE, FALSE, CHARACTER, NATURAL, INTEGER, FLOAT, AND,
	OR, NOT, IN, OUT, IF, THEN, ELSE, WHILE, DO, FOR, TO, TIPO,
	ARRAY, OF, RECORD, POINTER, NULL, NEW, DISPOSE, PROCEDURE,
	VAR, FORWARD
}
