package Scanner;

public enum CatLexica {
	BOOLEAN, TRUE, FALSE, CHARACTER, NATURAL, INTEGER, FLOAT, AND, OR, NOT, IN, OUT, IF, THEN, ELSE, WHILE, DO, FOR, TO, TIPO, ARRAY, OF, RECORD, POINTER, NULL, NEW, DISPOSE, PROCEDURE, VAR, FORWARD, SEP, DOSPUNTOS, DISTINTO, NFLOAT, MULT, CHAR, LLAVEDER, DESPIZQ, CORCHETEIZQ, BARRAV, IGUAL, CFLOAT, CNAT, DIV, ID, PYCOMA, EOF, ASIG, MAYOROIGUAL, ERROR, PCIE, MENOS, MENOR, MOD, MENOROIGUAL, MAYOR, DESPDER, PAP, FLECHA, CORCHETEDER, CINT, PUNTO, CCHAR, LLAVEIZQ, NNAT, MAS, COMA
}
